apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-booternetes-springone
spec:
  vendor: eduk8s.io
  title: The Cloud Native Java Workshop for SpringOne Tour 2021 
  description: Create your first Spring Boot application and deploy it to Kubernetes
  url: https://github.com/springone-tour-2021/booternetes-springone-tour-2021-workshop
  duration: 60m
  content: 
    image: jdk11-environment:*
    files: github.com/springone-tour-2021/booternetes-springone-tour-2021-workshop
  session:
    namespaces:
      budget: large
    resources:
      memory: 2Gi
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
        vendor: octant
      editor:
        enabled: true
      registry:
        enabled: true
      docker:
        enabled: true
